# Generated by Django 5.2.7 on 2025-10-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
